# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71999fc7cbf25237fd7c9d02dfb67aa2163327cb26a32eeaa051eddf7c725bbf8d3a492c84b7eab6fd6f6a1931d865520648ccf9d817ac85338cd207437c0699

test:
  secret_key_base: 1ebb5206f814331cc117b96b1eb91384d3f3303f3e3193330f0588a0f710a024ce84880a0f932762fd6bd7d0e0c13b06d355ffd79e00b40a649c965572769b05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
